### PR TITLE
Close graph editor if graph is deleted or project is closed

### PR DESCRIPTION
**Pull request by jensschmeink**
I added a connection to close the editor. The signal is triggered if the graph is deleted or (as it also deletes the graph) the project is closed.

### CODE REVIEW

**Comment by jensschmeink** [comment]
@mariusalexander this should be a simple approach to resolve the problem. Local tests should good results if the graph was removed from datamodel or the whole project has been closed.

**Comment by mariusalexander** [comment]
Thank you for given this issue a shot. Can you test what happens if you delete a (sub)graph? In case of a subgraph, ideally the editor should not close but the parent graph (another scene) should be displayed in the editor

**Comment by jensschmeink** [comment]
> Thank you for given this issue a shot. Can you test what happens if you delete a (sub)graph? In case of a subgraph, ideally the editor should not close but the parent graph (another scene) should be displayed in the editor

This was a problem that was not solved with the first line but I added few lines more to switch scene in case of an invalid scene

**Review by mariusalexander — APPROVED** [review]

**Comment by jensschmeink** [comment]
> @jensschmeink I performed minor refactoring and made it so, that the graph view can be used without a graph scene without any issues (e.g. crashes). This should make everything more robust. Please check the changes and _**squash & merge**_ (I do not see any reason to merge all commits separately)

Everything still seems to work as expected.

**Pull request merged**
